apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: oidc-bets
config:
  client_id: "kong"
  client_secret: "2g7EU6SXnrXTHkGlRqINfg2fKLrB4WH1"
  discovery: "http://keycloak.iam/realms/bets/.well-known/openid-configuration"
  introspection_endpoint: "http://keycloak.iam/realms/bets/protocol/openid-connect/token/introspect"
  #Utilizar chave publica para validar o JWT (jwks_uri)
  bearer_only: "yes"
  bearer_jwt_auth_enable: "yes"
  bearer_jwt_auth_allowed_auds:
    - account
plugin: oidc